services:
  
  ACM_SIGAI_db:
    image: postgres
    container_name: ACM_SIGAI_db
    environment:
      - POSTGRES_DB=acm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"

  django:
    build: .
    container_name: ACM_SIGAI_container
    image: acm_sigai
    ports:
      - "8000:8000"
    volumes:
      - .:/ACM_SIGAI
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - ACM_SIGAI_db

  PGAdmin:
    image: dpage/pgadmin4
    container_name: PGAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kephrem6@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - ACM_SIGAI_db
