# Generated by Django 5.1.1 on 2024-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clerk_user_id', models.CharField(max_length=255)),
                ('student_group', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
